### PR TITLE
Merge Dev version

### PR DESCRIPTION
**Pull request by BinaryMoon**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@BinaryMoon Try placing woocommerce-stubs.php as the last stub, it seems to depend on WP-CLI

**Comment by szepeviktor** [comment]
> Uncaught Error: Class 'Composer\Autoload\AutoloadGenerator' not found in /home/travis/build/BinaryMoon/jarvis/tests/woocommerce-stubs.php:59214

@BinaryMoon You have have stuffed some composer code into WC stubs.

Generally stubs should **only** contain code you use.

**Comment by BinaryMoon** [comment]
I didn't add it intentionally. I just ran your script. It must have been from the packages directory, that is needed for some WC_REST_Controller

**Comment by szepeviktor** [comment]
I see! Stubs should be generated from `packages/*/src/` only

**Comment by szepeviktor** [comment]
To be removed:

- packages/woocommerce-rest-api/src/Controllers/Version1
- packages/woocommerce-rest-api/src/Controllers/Version2

because there is Version3

**Comment by szepeviktor** [comment]
It getting nicer-and-nicer :)

**Comment by BinaryMoon** [comment]
It is :) It's not easy though. It's a lot of work to get this stuff up and running; especially when you don't really understand what you're doing.

I'm hoping that once it's all setup I won't have to think about it.

**Comment by szepeviktor** [comment]
This is the only service I provide (for developer teams)
click: https://twitter.com/szepeviktor/status/1172822556493189120

**Pull request merged**
